kubectl delete -f sonar-service.yaml
kubectl delete -f sonar-deployment.yaml
kubectl delete -f sonar-configmap.yaml
kubectl delete -f sonar-storage-extensions.yaml
kubectl delete -f sonar-storage-data.yaml
kubectl delete -f postgres-service.yaml
kubectl delete -f postgres-deployment.yaml
kubectl delete -f postgres-storage.yaml
kubectl delete -f postgres-secrets.yaml
kubectl delete -f namespace.yaml