kubectl apply -f namespace.yaml
kubectl apply -f postgres-secrets.yaml
kubectl apply -f postgres-storage.yaml
kubectl apply -f postgres-deployment.yaml
kubectl apply -f postgres-service.yaml
kubectl apply -f sonar-storage-data.yaml
kubectl apply -f sonar-storage-extensions.yaml
kubectl apply -f sonar-configmap.yaml
kubectl apply -f sonar-deployment.yaml
kubectl apply -f sonar-service.yaml