kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: sonarqube
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/zasadek/Desktop/Learning/Jenkins_EssT/sonarqube/postgres"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: sonarqube
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi