
apiVersion: v1
kind: PersistentVolume            
metadata:
  name: sonar-pv-data
  namespace: sonarqube
spec:
  storageClassName: standard  
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                       
    path: "/mnt/sonarqube/sonarqube"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 250Mi