apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv-extensions
  namespace: sonarqube
spec:
  storageClassName: standard
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/zasadek/Desktop/Learning/Jenkins_EssT/sonarqube/extensions"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 250Mi