pipeline {
  environment {
    dockerhub = credentials('dockerhub')
  }
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:3.8.1-adoptopenjdk-11
            command:
            - cat
            tty: true
          - name: buildx
            image: carlallen/docker:buildx
            tty: true
          - name: dind
            image: docker:20.10.16
            command:
                - cat
            tty: true
        '''
    }
  }
  stages {
    // stage('maven-build') {
    //   steps {
    //     container('maven') {
    //       sh 'mvn clean package -B -f bezkoder-app/pom.xml'
    //     }
    //   }
    // }
    // stage('unit_test') {
    //   steps {
    //     container('maven') {
    //       sh 'mvn test -Dtest=SpringBootDataJpaApplicationUnitTest -f bezkoder-app/pom.xml'
    //     }
    //   }
    // }
    // stage('integration_test') {
    //   steps {
    //     container('maven') {
    //       sh 'mvn test -Dtest=SpringBootDataJpaApplicationIntegrationTest -f bezkoder-app/pom.xml'
    //     }
    //   }
    // }
    // stage('dependency_scanning') {
    //   steps {
    //     container('maven') {
    //       sh 'mvn org.owasp:dependency-check-maven:check -DskipIntegrationTests -DskipUnitTests -f bezkoder-app/pom.xml'
    //     }
    //   }
    // }

    stage('build_and_push') {
      steps {
        container('buildx') {
          sh 'echo $dockerhub_PSW | docker login -u $dockerhub_USR --password-stdin'
          sh 'docker build -t docker.io/zakariaasadek/container_solutions_task:$CI_PIPELINE_IID bezkoder-app/. '
        }
      }
    }

    // stage('build_and_push') {
    //   agent any
    //   steps {
    //     sh 'echo $dockerhub_PSW | docker login -u $dockerhub_USR --password-stdin'
    //     sh 'docker build -t docker.io/zakariaasadek/container_solutions_task:$CI_PIPELINE_IID bezkoder-app/. '
    //   }
    // }
  }
}