pipeline {
  environment {
    dockerhub = credentials('dockerhub')
  }
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:3.8.1-adoptopenjdk-11
            command:
            - cat
            tty: true
          - name: buildx
            image: carlallen/docker:buildx
            tty: true
        '''
    }
  }
  stages {
    // stage('maven-build') {
    //   steps {
    //     container('maven') {
    //       sh 'mvn clean package -B -f bezkoder-app/pom.xml'
    //     }
    //   }
    // }
    // stage('unit_test') {
    //   steps {
    //     container('maven') {
    //       sh 'mvn test -Dtest=SpringBootDataJpaApplicationUnitTest -f bezkoder-app/pom.xml'
    //     }
    //   }
    // }
    // stage('integration_test') {
    //   steps {
    //     container('maven') {
    //       sh 'mvn test -Dtest=SpringBootDataJpaApplicationIntegrationTest -f bezkoder-app/pom.xml'
    //     }
    //   }
    // }
    // stage('dependency_scanning') {
    //   steps {
    //     container('maven') {
    //       sh 'mvn org.owasp:dependency-check-maven:check -DskipIntegrationTests -DskipUnitTests -f bezkoder-app/pom.xml'
    //     }
    //   }
    // }
    stage('build_and_push') {
      steps {
        container('buildx') {
          sh 'export DOCKER_BUILDKIT=1'
          sh 'echo $dockerhub'
          sh 'echo $dockerhub_PSW'
          sh 'echo $dockerhub_USR'
          sh 'echo $dockerhub_PSW | docker login -u $dockerhub_USR --password-stdin'
        //   sh 'docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY'
        //   sh 'docker login -u $DOCKER_ID -p $DOCKER_PASSWORD docker.io'
        //   sh 'docker login -u $GHCR_ORG -p $GHCR_TOKEN ghcr.io'
          sh 'export DOCKER_CLI_EXPERIMENTAL=enabled'
          sh 'docker buildx create --driver=docker-container --name=buildkit-builder --use'
          sh 'docker buildx inspect --bootstrap'
          sh 'docker buildx build --push --platform linux/amd64,linux/arm64 -t docker.io/zakariaasadek/container_solutions_task:$CI_PIPELINE_IID bezkoder-app/. '
        }
      }
    }
  }
}