pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:3.8.1-adoptopenjdk-11
            command:
            - cat
            tty: true
        '''
    }
  }
  stages {
    stage('maven-build') {
      steps {
        container('maven') {
          sh 'mvn clean package -B -f bezkoder-app/pom.xml'
        }
      }
    }
    stage('unit_test') {
      steps {
        container('maven') {
          sh 'mvn test -Dtest=SpringBootDataJpaApplicationUnitTest -f bezkoder-app/pom.xml'
        }
      }
    }
  }
}