name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-11-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with Maven
        run: |
          cd bezkoder-app
          mvn clean package -B
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bezkoder-app
          path: bezkoder-app/target/*.jar
          retention-days: 1
